name: Build and deploy PDFs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code + submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        persist-credentials: true

    # 2) Installe TeX Live et make
    - name: Install TeX Live and make
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          latexmk \
          make

    # 3) Compile les PDFs avec make
    - name: Build PDFs
      run: make

    # 4) Déploie le dossier docs/ sur la branche gh-pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs       # ce qui est dans docs/ est copié à la racine de gh-pages
        publish_branch: gh-pages  # on pousse tout dans gh-pages à la racine
        keep_files: false         # on remplace entièrement le contenu de gh-pages
        nojekyll: true            # crée automatiquement .nojekyll
  
    # (Optionnel) un message de succès
    - name: Success message
      run: echo "▶️ PDF built and deployed to gh-pages branch!"
